linters:
  enable:
    - gofmt
    - errcheck
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - gosec
    - bodyclose

linters-settings:
  gocyclo:
    min-complexity: 15
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - paramTypeCombine
  gosec:
    excludes:
      - G404
      - G101

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    - text: "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*print(f|ln)?|os\\.(Un)?Setenv). is not checked"
      linters:
        - errcheck
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true
  go: '1.21'

output:
  sort-results: true
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
