# Этап сборки
FROM golang:1.21-alpine

# Устанавливаем необходимые зависимости
RUN apk add --no-cache gcc musl-dev curl

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем только файлы с зависимостями
COPY go.mod go.sum ./

# Скачиваем зависимости
RUN go mod download

# Копируем исходный код
COPY . .

# Команда для запуска тестов
CMD ["go", "run", "./cmd/e2e/main.go"] 